<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\HSBM.Domain\HSBM.Domain.csproj" />
    <ProjectReference Include="..\..\src\HSBM.Application\HSBM.Application.csproj" />
    <ProjectReference Include="..\..\src\HSBM.Simulation\HSBM.Simulation.csproj" />
    <ProjectReference Include="..\..\src\HSBM.Persistence\HSBM.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
